# Generated by Django 5.1 on 2024-08-18 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0007_alter_cart_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.TimeField(db_index=True, null=True),
        ),
    ]
