# Generated by Django 5.1 on 2024-08-19 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0010_alter_orderitem_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_crew',
            field=models.ForeignKey(limit_choices_to={'groups_name': 'Delivery Crew'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivry_crew', to=settings.AUTH_USER_MODEL),
        ),
    ]
